name = "OntoLinker"
uuid = "12ad8390-0efd-45b7-9ef7-467bf1407207"
authors = ["Chris Damour"]
version = "1.0.0"

[deps]
Comonicon = "863f3e99-da2a-4334-8734-de3dacbe5542"
Configurations = "5218b696-f38b-4ac9-8b61-a12ec717816d"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
LightXML = "9c8b4983-aa76-5018-a973-4c85ecc9e179"
MetaGraphs = "626554b9-1ddb-594c-aa3c-2596fe9399a5"
OntologyLookup = "3c35c355-0acb-4572-93be-ae4d2e4cf8bf"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"


[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
